services:
  - type: web
    name: mediai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://medical-system-xi.vercel.app"
      - key: FRONTEND_URL
        value: "https://medical-system-xi.vercel.app"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          name: mediai-redis
          type: redis
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "MediAI <noreply@mediai.health>"
      - key: JITSI_APP_ID
        value: "mediai"
      - key: JITSI_SECRET
        sync: false

  - type: redis
    name: mediai-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
