# Generated by Django 4.2.28 on 2026-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_patient_6fe260_idx',
            old_name='appt_patient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_doctor__45f502_idx',
            old_name='appt_doctor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_schedul_2da7be_idx',
            old_name='appt_scheduled_at_idx',
        ),
        migrations.AlterField(
            model_name='consultationnote',
            name='assessment',
            field=models.TextField(help_text='Clinical assessment (NOT a diagnosis)'),
        ),
        migrations.AlterField(
            model_name='consultationnote',
            name='objective',
            field=models.TextField(blank=True, help_text='Examination findings'),
        ),
        migrations.AlterField(
            model_name='consultationnote',
            name='plan',
            field=models.TextField(help_text='Treatment plan and recommendations'),
        ),
        migrations.AlterField(
            model_name='consultationnote',
            name='subjective',
            field=models.TextField(help_text="Patient's complaints and history"),
        ),
    ]
