# Generated by Django 4.2.28 on 2026-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassessment',
            name='symptom_details',
            field=models.JSONField(default=dict, help_text='Follow-up answers'),
        ),
    ]
