# Generated by Django 4.2.28 on 2026-07-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctor_prof_verific_3715bb_idx',
            old_name='doctor_verification_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctor_prof_online__571a1d_idx',
            old_name='doctor_online_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctor_prof_special_4364c6_idx',
            old_name='doctor_specialization_idx',
        ),
    ]
